"""
Lektion 1 - ML-ramverk och arkitektur
Assignment: Frameworks, tensors, and execution models

Instructions:

1. Complete the tasks below with short, runnable code snippets
2. Run each section and observe the output
3. Comment your code to explain what each part does
4. Keep everything in this file unless stated otherwise
   """


## Task 1: Vector and matrix basics (NumPy)

### TODO: Create two vectors (length 3) and compute:


In [ ]:
import numpy as np

a = [5, 6, 9]
b = [7, 21, 2]
vector1 = np.array([1, 2, 3])
vector2 = np.array([5, 8, 13])

In [ ]:
# - dot product
print("Dot product is :", np.dot(a, b))
dot_prod = np.dot(vector1, vector2)
print("The dot product using two numpy arrays", dot_prod)
print("The dot product using a python list + python list", np.dot(a, b))
print("The dot product using a python list + numpy array", np.dot(a, vector1))

Dot product is : 179
The dot product using two numpy arrays 60
The dot product using a python list + python list 179
The dot product using a python list + numpy array 44


In [ ]:
# - L2 norm
l2_norm = np.linalg.norm(vector1)
print("L2_normalization for vector 1 is:", l2_norm)
l2_norm_vector2 = np.linalg.norm(vector2)
print("L2_normalization for vector 2 is:", l2_norm_vector2)

L2_normalization for vector 1 is: 3.7416573867739413
L2_normalization for vector 2 is: 16.06237840420901


In [ ]:
# - cosine similarity
cos_sim_v1_v2 = np.dot(vector1, vector2) / (l2_norm * l2_norm_vector2)
# same as above
cos_sim_v1_v2_ALTERNATIVE = dot_prod / (
    l2_norm * l2_norm_vector2
)  # we have variable name as dot_prod  and it is 60
print("The cosine similarity of vector1 and vector2 is :", cos_sim_v1_v2)
print("The cosine similarity of vector1 and vector2 is :", cos_sim_v1_v2_ALTERNATIVE)


The cosine similarity of vector1 and vector2 is : 0.9983374884595828
The cosine similarity of vector1 and vector2 is : 0.9983374884595828


### TODO: Create a 2x3 matrix and multiply it by a length-3 vector


In [ ]:
matris1 = [[2, 4, 7], [1, 5, 6]]

matrix_multiplication = matris1 @ vector1
print("Result of our matrix multiplication is:", matrix_multiplication)

Result of our matrix multiplication is: [31 29]


## Task 2: Eager vs graph execution

### TODO: Write a small function f(x) = x^3 + 2x


In [ ]:
def f(x):
    return x**3 + 2 * x


print("We test the funktion with 7, the answer is:", f(7))

We test the funktion with 7, the answer is: 357


### TODO: Implement f(x) in ONE of:


In [ ]:
import torch
x = torch.tensor(7.0)
y = f(x)
print(y)

tensor(357.)


- As a rule, PyTorch code is run in eager mode (one line at a time).
- If you use torch.compile, then it runs in graph mode.
- However, I believe this does not work on the MPS backend (Mac) and requires CUDA.


### TODO: Print the output and note how execution differs


In [ ]:
device = "cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu"
# device for amd

print(device)

cuda


### 1. Eager Execution (Standard)

In [ ]:
import time 
# Create a tensor with 10,000 random values drawn from a normal (Gaussian) distribution.
# If a CUDA-enabled GPU is available, the tensor is placed on the GPU.
# Otherwise, the tensor is created on the CPU.

x = torch.randn(10000, device="cuda" if torch.cuda.is_available() else "cpu")

# Record the current time before running the computation.
# This marks the start of the timing measurement.
start_time = time.time()

# Execute the function f(x), which applies the mathematical operation
# f(x) = x^3 + 2x element-wise to all 10,000 values in the tensor.
# The result is assigned to '_' to indicate that we do not care about
# the output values here, only that the computation is performed.
_ = f(x)

# Record the current time after the computation and subtract the start time.
# The result is the total time taken to execute the function f(x) in eager mode.
eager_time = time.time() - start_time

# Print the measured execution time in seconds.
# This shows how long it took to apply the function to all 10,000 elements.
print(f"Eager execution time: {eager_time} seconds")

Eager execution time: 0.0004260540008544922 seconds


### 2. Graph Execution (Compiled)

In [ ]:
try:
    compiled_f = torch.compile(f)
    start_time = time.time()
    _ = compiled_f(x)
    graph_time = time.time() - start_time
    print(f"Graph execution time: {graph_time} seconds")
except Exception as e:
    print("Graph execution time: N/A (torch.compile failed)")
    print("Reason:", e)


Graph execution time: N/A (torch.compile failed)
Reason: Cannot find a working triton installation. Either the package is not installed or it is too old. More information on installing Triton can be found at: https://github.com/triton-lang/triton

Set TORCHDYNAMO_VERBOSE=1 for the internal stack trace (please do this especially if you're reporting a bug to PyTorch). For even more developer context, set TORCH_LOGS="+dynamo"



## Task 3: Framework comparison in code
### TODO: Using scikit-learn, load the iris dataset

In [ ]:
from sklearn.datasets import load_iris

data = load_iris()

X = data['data']
y = data['target']

print(X)
print(y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

### TODO: Train a LogisticRegression model


In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X,y)

print(model.score(X,y))

0.9733333333333334


c:\Users\Lilit\Documents\GitHub\ML-Ramverk\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:
# TODO: Train a tiny MLP (MLPClassifier) on the same data
# TODO: Compare accuracy and write 3-5 comments in code about:
# - speed
# - API ergonomics
# - when you would pick each approach

print("Done! You now have a first hands-on view of ML frameworks.")
print("Keep these snippets for future comparison in later lessons.")

Done! You now have a first hands-on view of ML frameworks.
Keep these snippets for future comparison in later lessons.
