# Lecture 13 - Future trends and ethics

**Assignment: JAX jit + basic fairness checks**

Instructions:

1. Run a tiny JAX demo (or skip if unavailable)
2. Do a simple bias check with code
3. Write short reflections in comments

## Task 1: JAX jit demo

Try JAX jit on a small function and compare runtimes.

In [ ]:
# TODO: Create a simple function in JAX (e.g., matrix multiply)

import jax
import jax.numpy as jnp

# We define a function matMul that performs a matrix multiplication
def matMul(a,b):
    return a @ b


a = jnp.ones((200,200))

c = jnp.ones((1,1))
y = matMul(a, 4*a)
print(y)

[[800. 800. 800. ... 800. 800. 800.]
 [800. 800. 800. ... 800. 800. 800.]
 [800. 800. 800. ... 800. 800. 800.]
 ...
 [800. 800. 800. ... 800. 800. 800.]
 [800. 800. 800. ... 800. 800. 800.]
 [800. 800. 800. ... 800. 800. 800.]]


In [2]:
# We define another function that describes
# a straight line (the equation of a straight line)

def linear(x):
    k = 3
    m = 1
    y = k*x + m
    return y


print ("# The value of our function f(x) = kx + m, where k is 3 and m is 1, is:", linear(3))

f_linear = jax.jit(linear)

print ("# According to Jax, the value of our function f(x) = kx + m, where k is 3 and m is 1, is:", f_linear(3))

# We can let Jax calculate the derivative of our function (very useful)
df_linear = jax.grad(linear)

# Our derived function expects a float, since the derivative is undefined
# for integers (integers have no neighbors)
print("# The derivative of our function is:", df_linear(3.0))

# The value of our function f(x) = kx + m, where k is 3 and m is 1, is: 10
# According to Jax, the value of our function f(x) = kx + m, where k is 3 and m is 1, is: 10
# The derivative of our function is: 3.0


In [3]:
a

Array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], dtype=float32)

In [4]:
# TODO: Run once without jit and once with jit
import time

# In this cell we have two matrices
# a: 200 x 200 ones
# b: 200 x 200 sevens
a = jnp.ones((200,200))
b = 7 * jnp.ones((200,200))

# We perform the matrix multiplication (from our function)
# on the two matrices. We do it both raw,
# and with JAX/jit
start = time.perf_counter()
_ = matMul(a, b).block_until_ready()
t_nojit = time.perf_counter() - start

matmul_jit = jax.jit(matMul)
start = time.perf_counter()
_ = matmul_jit(a, b).block_until_ready()
t_jit = time.perf_counter() - start

print(f"JAX no-jit: {t_nojit:.4f}s, jit: {t_jit:.4f}s")


JAX no-jit: 0.0003s, jit: 0.0102s


In [ ]:
# TODO: Compare runtime and add 2-3 comment lines

# During the first run, Jit was slower than without it.
# In all subsequent runs, it was lightning fast.
# This is expected behavior, since JAX first
# maps out the logic for the network, and then executes!
# In the long run, JAX is much, much faster